#!/bin/bash

# Enable debugging and error handling
set -ex

echo "Adding apt-keys"
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5BA31D57EF5975CA
echo deb http://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list

# Add Docker GPG key and repository
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Minikube and kubectl
echo "Installing Minikube and kubectl"
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
sudo dpkg -i minikube_latest_amd64.deb
sudo apt-get install -y kubectl

# Ensure Docker is installed before starting Minikube
echo "Installing Docker"
sudo apt-get -y install docker-ce docker-ce-cli containerd.io > /dev/null 2>&1

# Start Minikube with VirtualBox as the driver
echo "Starting Minikube"
minikube start --driver=virtualbox

# Add kubectl to PATH
export PATH=$PATH:/usr/local/bin/kubectl

# Install Helm
echo "Installing Helm"
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# Install ArgoCD
echo "Installing ArgoCD"
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# Wait for Jenkins to start
while [ ! -f /var/lib/jenkins/secrets/initialAdminPassword ]; do
  sleep 5
done

# Additional installations and configurations
echo "Updating apt-get"
yes | sudo apt-get -qq update && yes | sudo apt-get -qq upgrade && yes | sudo apt-get -qq autoremove

echo "Installing default-java"
sudo apt-get -y install default-jre > /dev/null 2>&1
sudo apt-get -y install default-jdk > /dev/null 2>&1

echo "Installing git"
sudo apt-get -y install git > /dev/null 2>&1

# Wait for Jenkins to settle
sleep 10

# Installing Jenkins
echo "Installing jenkins"
sudo apt-get -y install jenkins > /dev/null 2>&1
sudo service jenkins start

# Wait for Jenkins to settle
sleep 30

# Installing Jenkins Plugins
echo "Installing Jenkins Plugins"
JENKINSPWD=$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)
echo $JENKINSPWD
